### PR TITLE
Update jerryscript to master

### PR DESCRIPTION
**Pull request by mikee47**
This PR updates jerryscript to current master branch. The current 2.4 release was in January so like there will be another before too long and makes sense to base further work on that.

The API has changed slightly (for the better!) and there are lots of fixes and improvements.

Building the snapshot tool on Windows now uses the MinGW compiler rather than the default Visual Studio tools, which aren't part of the Sming installation. (They're a pain to install as well.)

### CODE REVIEW

**Comment by mikee47** [comment]
Discussion on changes to public API in master and due in next release https://github.com/jerryscript-project/jerryscript/issues/4186

**Comment by slaff** [comment]
@mikee47 Can you add here library CI as suggested in https://github.com/SmingHub/Sming/pull/2434 ?

**Comment by mikee47** [comment]
@slaff Repo. doesn't need any changes, follow instructions here https://github.com/SmingHub/Sming/tree/develop/Tools/ci/library

**Comment by mikee47** [comment]
(I've done it - forgot I had access!)

**Comment by slaff** [comment]
> (I've done it - forgot I had access!)

Thanks a lot! I need CI also for the pull requests but let me see if I can find the needed settings...

**Comment by mikee47** [comment]
@slaff the Windows ESP32 build overran, got a PR to fix that by splitting out each SOC as usual.

**Comment by mikee47** [comment]
@slaff If you want to check the new fix use `https://raw.githubusercontent.com/mikee47/Sming/feature/appveyor-byoc/Tools/ci/library/appveyor.txt` as the custom yaml

**Pull request merged**
