### PR TITLE
Fix compiler warning about deprecated std::iterator

### PR DESCRIPTION
**Pull request by mikee47**

### CODE REVIEW

**Comment by mikee47** [comment]
@slaff I'm working on a bunch of updates to fix current batch of CI warnings for Sming

**Comment by slaff** [comment]
@mikee47 is this PR ready? I can see multiple issues in the CI system but they can be addressed in another PR too.

**Comment by mikee47** [comment]
Yep, nice and simple this one :-)

**Comment by slaff** [comment]
Thank you @mikee47 !!!

**Pull request merged**
