### PR TITLE
Update jerryscript to current release 2.4

### PR DESCRIPTION
**Pull request by mikee47**
Use main jerryscript repository and patch version 2.4.

todo:

* [x] Fix Windows host builds
* [x] Fix rp2040 builds (missing math library)
* [x] Use variant for snapshot builder, depends on whether JERRY_ESNEXT is defined or not
* [x] Fix documentation
* [x] Fix docker files
~~* [ ] Investigate whether emscripten can be implemented without patching jerryscript~~ Look at separately

### CODE REVIEW

**Comment by slaff** [comment]
Wow! So far this PR looks awesome :) Thanks a lot @mikee47

**Comment by mikee47** [comment]
@slaff Dockerfile should be fixed now, have updated everything to more recent versions. Tested with:

```
docker build -f Dockerfile -t jerryscript-ems . --build-arg JERRY_REPO=https://github.com/mikee47/Sming-jerryscript --build-arg JERRY_BRANCH=feature/jerryscript-2.4
```

**Comment by slaff** [comment]
@mikee47 Shall I merge this PR or you would like to add more things to it?

**Comment by mikee47** [comment]
@slaff Yes, all done I think. As noted above there may be a way to simplify this without having to patch jerryscript, if I think of something I'll open another PR.

**Pull request merged**
