### PR TITLE
Updates before initial release

### PR DESCRIPTION
**Pull request by mikee47**
Some additional revisions which should be considered before release.

**fixes**

- Update 'load' and 'eval' functions, they return a value, not bool
- Tidy up `Object::getFunction` to return only requested function or error
- Fix Value move constructor / assignment operator, reset()
- Fix `Value::isEmpty()` and String() operator
- Prevent `Null`, `Undefined` from being constructed with different values.
- Must not use internal jerryscript headers publicly. Can introduce invalid #defines.

**improvements**

- Enable snapshot compiler error messages. e.g. shows position of syntax errors in .js
- Update Advanced_Jsvm README. Remove diagram, etc. which is in main library README, and re-word appropriately.
- Add JERRY_ERROR_MESSAGES variable, optionally include library messages
- Generate type maps from jerryscript headers. Avoids manual copying of values which may change in future releases.
- Add feature test, i.e. JS::isFeatureEnabled()
- Only enable JERRY_ENABLE_DEBUG explicitly; should only be required for jerryscript library debugging.
- Additional tests.
- Enable parser support via `JERRY_PARSER` variable - `eval()` won't work without this.

Known issues;

- For esp8266, constant data cannot be easily moved to flash as accesses are not always word aligned. This will be more involved and handled as a separate PR.
- Fatal errors are not handled and will cause system reset. See #10.
- Whilst `eval()` will work with parser support enabled, the main parse/run interfaces are more extensive and have not yet been ported.

### CODE REVIEW

**Comment by slaff** [comment]
> Things to consider before release?

Looks good to me. Ping me when ready with this PR to review it and merge it.

**Comment by slaff** [comment]
@mikee47 Ready with this PR?

**Comment by mikee47** [comment]
@slaff Just re-running CI for that last change https://ci.appveyor.com/project/mikee47/jerryscript/builds/41950890 then done here.

**Comment by mikee47** [comment]
@slaff OK, all clear

**Pull request merged**
